### ISSUE TITLE
Fails trying to create native version on Windows

### ISSUE THREAD

**Issue by MattyBalaam** [schnerd/ckmeans#1]
I'm trying to just use this module purely as an in-browser cross-platform solution.

I initally installed on a Mac machine and had no problems, but trying on a Windows machine I get errors trying to build the native modules. 

Note that the native solution is not required. 

```
...\node_modules\ckmeans\src\native\./ckmeans.c(108): error C2057: expected constant expression [....\node_modules\ckmeans\build\ckmeans.vcxproj]
...\node_modules\ckmeans\src\native\./ckmeans.c(108): error C2466: cannot allocate an array of constant size 0 [....\node_modules\ckmeans\build\ckmeans.vcxproj]
...\node_modules\ckmeans\src\native\./ckmeans.c(108): error C2133: 'sumX': unknown size [....\node_modules\ckmeans\build\ckmeans.vcxproj]
...\node_modules\ckmeans\src\native\./ckmeans.c(109): error C2057: expected constant expression [....\node_modules\ckmeans\build\ckmeans.vcxproj]
...\node_modules\ckmeans\src\native\./ckmeans.c(109): error C2466: cannot allocate an array of constant size 0 [....\node_modules\ckmeans\build\ckmeans.vcxproj]
...\node_modules\ckmeans\src\native\./ckmeans.c(109): error C2133: 'sumXsq': unknown size [....\node_modules\ckmeans\build\ckmeans.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ....\node_modules\ckmeans
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

```

EDIT: paths shortened

**Comment by smashmiek** [comment]
I'm getting this too.  Can confirm that other packages using node-gyp do work.

PS C:\WINDOWS\system32\testing> npm install --save-dev ckmeans

> ckmeans@1.0.1 install C:\WINDOWS\system32\testing\node_modules\ckmeans
> node-gyp rebuild


C:\WINDOWS\system32\testing\node_modules\ckmeans>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_
modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
"C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
62:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\testing\node_modules\ckmeans
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN testing@1.0.0 No description
npm WARN testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ckmeans@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by sebastianoscarlopez** [comment]
Same issue here
C:\Users\sebas\Documents\monitorseguridad\node_modules\ckmeans\src\native\ckmeans.c(108,24): error C2057: expected constant expression [C:\Users\sebas\Documents\monitorseguridad\node_modules\ckmeans\build\ckmeans.vcxproj]

**Comment by schnerd** [comment]
I'm thinking it probably makes sense to split this package into ckmeans & ckmeans-native, considering the code between the two is pretty much mutually exclusive and the native feature seems to create more problems than it solves for many users of this package.

But if anyone has a fix for this windows-specific issue, feel free to submit a PR.

**Comment by Eh2406** [comment]
Umm... I did make a PR... https://github.com/schnerd/ckmeans/pull/3

**Comment by schnerd** [comment]
Apologies, hadn't clicked over to the PR tab when I wrote that comment and didn't see the PR referenced on this issue. I'll take a look at it, thank you for contributing.

I also don't own a windows machine, so if anyone else wants to review or test that change that would be amazing. Otherwise I may need to download a window virtual machine or find a cloud-based one to test with.

**Comment by Eh2406** [comment]
It works on my machine, but that don't mean much. Github Actions supports windows and I think is easy to set up, if you are looking for a CI based solution.

**Comment by schnerd** [comment]
I merged @Eh2406's change and also split this package into separate ckmeans and ckmeans-native packages to avoid unnecessary hurdles for most users. Also set up github actions to confirm that the new change works on windows. Thanks for the patience folks and let me know if you see any further issues!
