### ISSUE TITLE
Prebuilt package

### ISSUE THREAD

**Issue by vbanos** [schnerd/ckmeans#2]
Your excellent package is quite useful for our team.

Have you considered providing a prebuilt JS package that does not require C compilation during installation? That would save people a lot of effort.
Its not always easy to have a C build environment in production deployments.

Thank you!

**Comment by schnerd** [comment]
Can you clarify what you mean by "prebuilt JS package"? My knowledge of publishing native addons for node is relatively basic (current solution was contributed by someone in a PR), but I assumed compilation is needed to match the architecture of the machine the package is being installed on?

As a side note, I'm thinking it might make sense to split this package into ckmeans & ckmeans-native, considering the code between the two is pretty much mutually exclusive and the native feature probably creates more problems than it solves for many users of this package.

**Comment by schnerd** [comment]
The project has now been split into a `ckmeans` and `ckmeans-native` package, hopefully that helps!
